class TelrPaymentModel {
  String storeId,
      key,
      deviceType,
      deviceId,
      appName,
      userId,
      description,
      currency,
      amount,
      language,
      userName,
      userFirstName,
      userSecondName,
      address,
      city,
      region,
      country,
      userPhoneNumber,
      email;

  TelrPaymentModel({
    required this.storeId,
    required this.key,
    required this.deviceType,
    required this.deviceId,
    required this.appName,
    required this.userId,
    required this.description,
    required this.currency,
    required this.amount,
    required this.language,
    required this.userName,
    required this.userFirstName,
    required this.userSecondName,
    required this.address,
    required this.city,
    required this.region,
    required this.country,
    required this.userPhoneNumber,
    required this.email,
  });
}
